# Get all trips
GET http://localhost:8080/trips
Accept: application/json

###

#Get trip by id
GET http://localhost:8080/trips/6987c1dae7337a2f7ebf35b1
Accept: application/json

###

# Get all attractions
GET http://localhost:8080/attractions
Accept: application/json

###

#Get attractions by id
GET http://localhost:8080/attractions/6987c1c7e7337a2f7ebf35ab
Accept: application/json

###

#insert trip
POST http://localhost:8080/trips/
Content-Type: application/json
Accept: application/json

{
    "name": "super awesome trip",
    "startDate": "11/21/2027",
    "endDate": "10/21/2027",
    "parkList": ["Magic Kingdome", "Hollwood Studios"],
    "hotel": "",
    "budget": 0,
    "notes": ""
}

###

#insert attraction
POST http://localhost:8080/attractions/698beb3f25f6b37b00ee719f
Content-Type: application/json
Accept: application/json

{
    "name": "Rise of the resistance",
    "park": "Hollywood studios",
    "waitTime": 50,
    "type": "Dark Ride"
}

###

#edit trip
PUT http://localhost:8080/trips/6987c1dae7337a2f7ebf35b0
Content-Type: application/json
Accept: application/json

{

    "budget": 1000
    
}

###

#edit attraction
PUT http://localhost:8080/attractions/698beb3f25f6b37b00ee719f
Content-Type: application/json
Accept: application/json

{
    "name": "Rise of the Resistance",
    "park": "Hollywood studios",
    "waitTime": 50,
    "type": "Dark Ride"
}

###

#delete trip
DELETE http://localhost:8080/trips/698bbf51b0ff8371b9857f59

Accept: application/json



###

#delete attraction
DELETE http://localhost:8080/attractions/698a979860a557c685998364

Accept: application/json




