# Get all trips
GET http://localhost:8080/trips
Accept: application/json

###

#Get trip by id
GET http://localhost:8080/trips/6987c1dae7337a2f7ebf35b0
Accept: application/json

###

# Get all attractions
GET http://localhost:8080/attractions
Accept: application/json

###

#Get attractions by id
GET http://localhost:8080/attractions/6987c1c7e7337a2f7ebf35ab
Accept: application/json

###

#insert trip
POST http://localhost:8080/trips/
Content-Type: application/json
Accept: application/json

{
    "name": "Summer Vacation 2026",
    "startDate": "2026-07-10",
    "endDate": "2026-07-17",
    "parkList": ["Epcot", "Animal Kingdom"],
    "hotel": "Disney's Polynesian Village",
    "budget": 5000,
    "notes": "Book FastPasses in advance"
}

###

#insert attraction
POST http://localhost:8080/attractions
Content-Type: application/json
Accept: application/json

{
    "name": "Slinky Dog Dash",
    "park": "Hollywood Studios",
    "waitTime": 50,
    "type": "Family Ride"
}

###

#edit trip
PUT http://localhost:8080/trips/
Content-Type: application/json
Accept: application/json

{

    "budget": 5000
    
}

###

#edit attraction
PUT http://localhost:8080/attractions/6987f24595d191717375eed3
Content-Type: application/json
Accept: application/json

{

    "waitTime": 0
    
}

###

#delete trip
DELETE http://localhost:8080/trips/698a979860a557c685998364

Accept: application/json



###

#delete attraction
DELETE http://localhost:8080/attractions/698a979860a557c685998364

Accept: application/json




