# Get all trips
GET http://localhost:8080/trips
Accept: application/json
x-dev-bypass: true

###

#Get trip by id
GET http://localhost:8080/trips/6987d57c0be5bd4c96544d0e
Accept: application/json
x-dev-bypass: true

###

# Get all attractions
GET http://localhost:8080/attractions
Accept: application/json
x-dev-bypass: true

###

#Get attractions by id
GET http://localhost:8080/attractions/6987c1c7e7337a2f7ebf35ad
Accept: application/json
x-dev-bypass: true

###

#insert trip
POST http://localhost:8080/trips/
Content-Type: application/json
Accept: application/json
x-dev-bypass: true

{
    "name": "Winter Trip",
    "startDate": "2027-11-21",
    "endDate": "2027-11-28",
    "parkList": ["Magic Kingdome", "Hollwood Studios","EPCOT"],
    "hotel": "Polly",
    "budget": 7000,
    "notes": "See if there are parties available"
}

###

#insert attraction
POST http://localhost:8080/attractions/
Content-Type: application/json
Accept: application/json
x-dev-bypass: true

{
    "name": "new ride",
    "park": "EPCOT",
    "waitTime": 50,
    "rideType": "new ride"
}

###

#edit trip
PUT http://localhost:8080/trips/69a3028e14698b15c2890706
Content-Type: application/json
Accept: application/json
x-dev-bypass: true

{
    "name": "Spring Break",
    "startDate": "2026-03-15",
    "endDate": "2026-03-21",
    "parkList": ["Magic Kingdome", "Hollwood Studios", "EPCOT"], 
    "hotel": "Polly",
    "budget": 6000,
    "notes": "Remember to book reservations at Boma"   
}

###

#edit attraction
PUT http://localhost:8080/attractions/69a302de14698b15c2890707
Content-Type: application/json
Accept: application/json
x-dev-bypass: true

{
    "name": "Moana Water Experiance",
    "park": "EPCOT",
    "waitTime": 15,
    "rideType": "Walk throught experiance"
}

###

#delete trip
DELETE http://localhost:8080/trips/69a3028e14698b15c2890706
Accept: application/json
x-dev-bypass: true



###

#delete attraction
DELETE http://localhost:8080/attractions/69a302de14698b15c2890707
Accept: application/json
x-dev-bypass: true




